// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jknkzphysctosqlhcqrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprbmt6cGh5c2N0b3NxbGhjcXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwOTIyOTYsImV4cCI6MjA1NDY2ODI5Nn0.LLk4Y26n9kh9HWLm3uzsK9SqYTl8GAATEkZJKJ1cidM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);